# Generated by Django 3.2.8 on 2022-01-21 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestaurantID', models.CharField(max_length=100)),
                ('RestaurantName', models.CharField(max_length=100)),
                ('Amount', models.FloatField()),
                ('isPaid', models.BooleanField(default=False)),
                ('OrderDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodId', models.CharField(max_length=100)),
                ('FoodImage', models.CharField(max_length=1000)),
                ('FoodTitle', models.CharField(max_length=100)),
                ('FoodPrice', models.IntegerField()),
                ('FoodQuantity', models.IntegerField()),
                ('RatingCount', models.FloatField()),
                ('orderID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paytm.foodorder')),
            ],
        ),
    ]
